rule blast_vs_hybrid:
    input:
        fasta_dir="/mnt/c/Users/Carlos/Documents/Sequences/Alignments/Seq_4_alignment"
    output:
        directory("/mnt/c/Users/Carlos/Documents/Sequences/Alignments/Blast_results")
    params:
        script="run_blastn_ref.sh"
    shell:
        "bash {params.script} {input.fasta_dir} {output}"

rule blastn:
    input:
        fasta_dir="/mnt/c/Users/Carlos/Documents/Sequences/Hybrid/Unicycler_assemblies"
    output:
        directory("/mnt/c/Users/Carlos/Documents/Sequences/Hybrid/Blast_results")
    params:
        script="run_blastn.sh"
    shell:
        "bash {params.script} {input.fasta_dir} {output[0]}"

rule unicycler_assemblies:
    input:
        illumina_reads="/mnt/c/Users/Carlos/Documents/Sequences/Illumina/Fastp_trimming",
        nanopore_reads="/mnt/c/Users/Carlos/Documents/Sequences/Nanopore/Fastplong_Porechop_trimming_Q10"
    output:
        directory="/mnt/c/Users/Carlos/Documents/Sequences/Hybrid/unicycler_assemblies"
    params:
        script="run_unicycler_H.sh"
    shell:
        "bash {params.script} {input.illumina_reads} {input.nanopore_reads} {output[0]}"
