rule nanoplot_quality_check:
    input:
        dir="/mnt/d/Documentos/Sequences/Nanopore/Raw_data"
    output:
        directory("/mnt/d/Documentos/Sequences/Nanopore/NanoPlot_reports")
    params:
        script="run_nanoplot.sh"
    shell:
        "bash {params.script} {input.dir} {output[0]}"

rule fastplong_trimming:
    input:
        dir="/mnt/d/Documentos/Sequences/Nanopore/Raw_data"
    output:
        directory("/mnt/d/Documentos/Sequences/Nanopore/Fastplong_trimming_Q6")
    params:
        script="run_fastplong.sh"
    shell:
        "bash {params.script} {input.dir} {output[0]}"

rule unicycler_assemblies:
    input:
        dir="/mnt/d/Documentos/Sequences/Nanopore/Fastplong_trimming_Q6"
    output:
        directory("/mnt/d/Documentos/Sequences/Nanopore/Unicycler_assembly_Q6")
    params:
        script="run_unicycler_N.sh"
    shell:
        "bash {params.script} {input.dir} {output[0]}"

rule canu_assembly:
    input:
        nanopore_dir="/mnt/d/Documentos/Sequences/Nanopore/Fastplong_trimming_Q10"
    output:
        directory("/mnt/d/Documentos/Sequences/Nanopore/Canu_assembly_Q10")
    params:
        script="run_canu.sh"
    shell:
        "bash {params.script} {input.nanopore_dir} {output[0]}"