rule blastn:
    input:
        fasta_dir="/mnt/c/Users/Carlos/Documents/Sequences/Illumina/Unicycler_assemblies"
    output:
        directory("/mnt/c/Users/Carlos/Documents/Sequences/Illumina/Blast_results")
    params:
        script="run_blastn.sh"
    shell:
        "bash {params.script} {input.fasta_dir} {output[0]}"